config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end

  namespace :users_backoffice do
    get 'welcome/index'
    get 'profiles', to: 'profiles#edit'
    patch 'profiles', to: 'profiles#update'
    get 'zip_code', to: 'zip_code#show'
  end

  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
    resources :subjects
    resources :questions
  end
  
  devise_for :admins, skip: [:registrations]
  devise_for :users

  get 'home', to: 'site/welcome#index'
  get 'backoffice', to: 'admins_backoffice/welcome#index'

  root to: 'site/welcome#index'
  
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  before_action :verify_password, only: [:update]
  
  def index
    console
    @admins = Admin.all.page(params[:page])
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Administrador criado!" 
    else
      render :new, notice: "Não foi possível criar um novo administrador!" 
    end
  end


  def edit
  end

  def update
    if @admin.update(admin_params)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to admins_backoffice_admins_path, notice: "Informações atualizadas!" 
    else
      render :edit, notice: "Não foi possível atualizar sua informações!" 
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Administrador removido!" 
    else
      render :index
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end
  
  def admin_params
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only: [:new, :edit]
  
  def index
    @questions = Question.includes(:subject).order(:description).page(params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: "Pergunta criado!" 
    else
      render :new, notice: "Não foi possível criar uma nova pergunta!" 
    end
  end


  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to admins_backoffice_questions_path, notice: "Informações atualizadas!" 
    else
      render :edit, notice: "Não foi possível atualizar suas informações!" 
    end
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Pergunta removida!" 
    else
      render :index, notice: "Não foi possível remover a pergunta!"
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end
  
  def question_params
    params.require(:question).permit(:description, :subject_id, answers_attributes: [:id, :description, :correct, :_destroy])
  end

  def get_subjects
    @subjects = Subject.all
  end

end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update, :destroy]
  
  def index
    respond_to do |format|
      format.html { @subjects = Subject.all.order(:description).page(params[:page]) }
      format.pdf { @subjects = Subject.all.order(:description) }
      format.json { @subjects = Subject.all.order(:description) }
    end
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área criado!" 
    else
      render :new, notice: "Não foi possível criar um novo assunto/área!" 
    end
  end


  def edit
  end

  def update
    if @subject.update(subject_params)
      redirect_to admins_backoffice_subjects_path, notice: "Informações atualizadas!" 
    else
      render :edit, notice: "Não foi possível atualizar sua informações!" 
    end
  end

  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área removido!" 
    else
      render :index, notice: "Não foi possível remover o assunto/área!"
    end
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end
  
  def subject_params
    params.require(:subject).permit(:description)
  end

end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  
  def index
    @total_users = AdminStatistic.total_users

    @total_questions = AdminStatistic.total_questions
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'

end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil, method = nil)
    (object && method) ? object.model.human_attribute_name(method) : "Informe corretamente os dados"
  end
end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form.html',
    locals: { action_message: t('messages.editing', model: @subject.model_name.human)} %>

app/views/admins_backoffice/subjects/index.html.erb
<div class="flex-row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= t('messages.listing', model: @subjects.model_name.human(count: 2)) %></h1>
  </div>
</div>

<hr class="sidebar-divider">

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th><%= translate_attribute(@subjects, :description) %></th>
        <th>
          <%= link_to new_admins_backoffice_subject_path, class:"btn btn-success btn-circle" do %>
            <i class="fa fa-plus"></i>
          <% end %>
          <%= link_to admins_backoffice_subjects_path(format: :pdf), class:"btn btn-danger btn-circle" do %>
            <i class="fa fa-file-pdf"></i>
          <% end %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @subjects.each do |subject| %>
        <tr>
          <td><%= subject.id %></td>
          <td><%= subject.description %></td>
          <td style = "width: 200px">
            <%= link_to edit_admins_backoffice_subject_path(subject), class:"btn btn-primary btn-circle" do %>
              <i class="fa fa-edit"></i>
            <% end %>
            
           <%= link_to admins_backoffice_subject_path(subject), method: :delete, class:"btn btn-danger btn-circle", data: {confirm: t('messages.confirm_exclusion')} do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex justify-content-center">
    <%= paginate @subjects %>
  </div>

</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form.html', 
    locals: { action_message: t('messages.new', model: @subject.model_name.human)} %>